"""Causal session features for overnight-range breakout trade selection."""

from __future__ import annotations

from dataclasses import dataclass

import polars as pl


REQUIRED_LEDGER_COLUMNS = {
    "session_date", "status", "side", "range_high", "range_low", "range_open", "range_close",
    "range_size", "range_pips", "entry_timestamp", "entry_price", "gross_pnl_pips", "exit_reason",
    "range_coverage", "trade_coverage",
}
REQUIRED_BAR_COLUMNS = {
    "timestamp",
    "bid_open", "bid_high", "bid_low", "bid_close",
    "ask_open", "ask_high", "ask_low", "ask_close",
}


@dataclass(frozen=True)
class OvernightRangeFeatureConfig:
    """Causal daily-history settings and data-quality requirements."""

    daily_range_windows: tuple[int, ...] = (5, 20)
    moving_average_window: int = 20
    minimum_range_coverage: float = 1.0
    minimum_trade_coverage: float = 1.0

    def __post_init__(self) -> None:
        if not self.daily_range_windows or any(window < 1 for window in self.daily_range_windows):
            raise ValueError("daily_range_windows must contain positive window lengths.")
        if self.moving_average_window < 1:
            raise ValueError("moving_average_window must be positive.")
        if not 0 <= self.minimum_range_coverage <= 1 or not 0 <= self.minimum_trade_coverage <= 1:
            raise ValueError("minimum coverage values must be in [0, 1].")


def _validate_columns(frame: pl.DataFrame, required: set[str], name: str) -> None:
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(f"{name} is missing required columns: {', '.join(missing)}.")


def _daily_history(bars: pl.DataFrame, config: OvernightRangeFeatureConfig) -> pl.DataFrame:
    daily = (
        bars.sort("timestamp")
        .with_columns([
            ((pl.col(f"bid_{field}") + pl.col(f"ask_{field}")) / 2).alias(f"_mid_{field}")
            for field in ("open", "high", "low", "close")
        ] + [pl.col("timestamp").dt.convert_time_zone("Europe/London").dt.date().alias("session_date")])
        .group_by("session_date", maintain_order=True)
        .agg([
            pl.col("_mid_open").first().alias("daily_open"),
            pl.col("_mid_high").max().alias("daily_high"),
            pl.col("_mid_low").min().alias("daily_low"),
            pl.col("_mid_close").last().alias("daily_close"),
        ])
        .sort("session_date")
        .with_columns((pl.col("daily_high") - pl.col("daily_low")).alias("daily_range"))
        .with_columns([
            pl.col(name).shift(1).alias(f"previous_{name}")
            for name in ("daily_open", "daily_high", "daily_low", "daily_close", "daily_range")
        ])
    )
    expressions: list[pl.Expr] = [
        pl.col("daily_range").shift(1).rolling_mean(window_size=window).alias(f"adr_{window}")
        for window in config.daily_range_windows
    ]
    expressions.append(
        pl.col("daily_close").shift(1).rolling_mean(window_size=config.moving_average_window)
        .alias(f"price_ma_{config.moving_average_window}")
    )
    return daily.with_columns(expressions)


def overnight_range_feature_columns(config: OvernightRangeFeatureConfig = OvernightRangeFeatureConfig()) -> list[str]:
    """Return model-input columns generated by :func:`build_overnight_range_features`."""
    columns = [
        "range_pips",
        "overnight_return_to_range",
        "overnight_close_position",
        "previous_daily_range_pips",
        "previous_daily_return_to_range",
        "range_to_previous_daily_range",
        "range_to_previous_overnight_range",
        "overnight_high_position_in_previous_day",
        "overnight_low_position_in_previous_day",
        "overnight_inside_previous_day",
        "side_is_long",
        "entry_with_previous_day_direction",
        "entry_hour_london",
        "entry_minute_london",
        "entry_to_ma_pips",
        "previous_close_to_ma_pips",
    ]
    columns.extend(f"range_to_adr_{window}" for window in config.daily_range_windows)
    columns.extend(f"weekday_{weekday}" for weekday in range(1, 6))
    return columns


def build_overnight_range_features(
    ledger: pl.DataFrame,
    bars: pl.DataFrame,
    config: OvernightRangeFeatureConfig = OvernightRangeFeatureConfig(),
) -> tuple[pl.DataFrame, list[str]]:
    """Return feature-ready entered trades and causal model column names.

    ``r_return`` is the realized risk-normalized return and is the regression
    target for trade selection. ``target`` remains a convenient positive-return
    indicator for diagnostics. Daily fields are shifted by one observed London
    trading day, so no current-day future prices enter the feature set.
    """
    _validate_columns(ledger, REQUIRED_LEDGER_COLUMNS, "ledger")
    _validate_columns(bars, REQUIRED_BAR_COLUMNS, "bars")
    if "r_return" not in ledger.columns:
        if "r_multiple" not in ledger.columns:
            raise ValueError("ledger is missing r_return (or the legacy r_multiple column).")
        ledger = ledger.with_columns(pl.col("r_multiple").alias("r_return"))
    daily = _daily_history(bars, config)
    features = (
        ledger.sort("session_date")
        .with_columns(
            pl.col("range_size").fill_null(strategy="forward").shift(1).alias("previous_overnight_range")
        )
        .filter(
            (pl.col("status") == "entered")
            & (pl.col("range_coverage") >= config.minimum_range_coverage)
            & (pl.col("trade_coverage") >= config.minimum_trade_coverage)
            & pl.col("gross_pnl_pips").is_not_null()
        )
        .join(daily, on="session_date", how="left")
    )
    features = features.with_columns([
        ((pl.col("range_close") - pl.col("range_open")) / pl.col("range_size")).alias("overnight_return_to_range"),
        ((pl.col("range_close") - pl.col("range_low")) / pl.col("range_size")).alias("overnight_close_position"),
        (pl.col("previous_daily_range") / 0.0001).alias("previous_daily_range_pips"),
        ((pl.col("previous_daily_close") - pl.col("previous_daily_open")) / pl.col("previous_daily_range")).alias("previous_daily_return_to_range"),
        (pl.col("range_size") / pl.col("previous_daily_range")).alias("range_to_previous_daily_range"),
        (pl.col("range_size") / pl.col("previous_overnight_range")).alias("range_to_previous_overnight_range"),
        ((pl.col("range_high") - pl.col("previous_daily_low")) / pl.col("previous_daily_range")).alias("overnight_high_position_in_previous_day"),
        ((pl.col("range_low") - pl.col("previous_daily_low")) / pl.col("previous_daily_range")).alias("overnight_low_position_in_previous_day"),
        ((pl.col("range_high") <= pl.col("previous_daily_high")) & (pl.col("range_low") >= pl.col("previous_daily_low"))).cast(pl.Int8).alias("overnight_inside_previous_day"),
        (pl.col("side") == "long").cast(pl.Int8).alias("side_is_long"),
        (((pl.col("side") == "long") & (pl.col("previous_daily_close") > pl.col("previous_daily_open")))
         | ((pl.col("side") == "short") & (pl.col("previous_daily_close") < pl.col("previous_daily_open")))).cast(pl.Int8).alias("entry_with_previous_day_direction"),
        pl.col("entry_timestamp").dt.convert_time_zone("Europe/London").dt.hour().alias("entry_hour_london"),
        pl.col("entry_timestamp").dt.convert_time_zone("Europe/London").dt.minute().alias("entry_minute_london"),
        ((pl.col("entry_price") - pl.col(f"price_ma_{config.moving_average_window}")) / 0.0001).alias("entry_to_ma_pips"),
        ((pl.col("previous_daily_close") - pl.col(f"price_ma_{config.moving_average_window}")) / 0.0001).alias("previous_close_to_ma_pips"),
        (pl.col("gross_pnl_pips") > 0).cast(pl.Int8).alias("target"),
    ] + [
        (pl.col("range_size") / pl.col(f"adr_{window}")).alias(f"range_to_adr_{window}")
        for window in config.daily_range_windows
    ] + [
        (pl.col("session_date").dt.weekday() == weekday).cast(pl.Int8).alias(f"weekday_{weekday}")
        for weekday in range(1, 6)
    ])
    columns = overnight_range_feature_columns(config)
    dataset = features.drop_nulls(columns + ["target"])
    for column in columns:
        if dataset.schema[column].is_numeric():
            dataset = dataset.filter(pl.col(column).is_finite())
    return dataset, columns
